"""
Amazon logo , search by Xpath, "//i[@class='a-icon a-icon-logo']"
Continue button, search by ID, "continue"
Need help link, search by Xpath, "//span[@class='a-expander-prompt']"
Forgot your password link, search by ID, "auth-fpp-link-bottom"
Other issues with Sign-In link, search by ID, "ap-other-signin-issues-link"
Create your Amazon account button, search by ID, "createAccountSubmit"
*Conditions of use link, search by Xpath, "//a[contains(@href, 'footer_cou')]"
*Privacy Notice link, search by Xpath, "//a[contains(@href, 'footer_privacy')]"
"""